version: '3.5'

services:
  lab:
    container_name: jupyterlab
    build:
      context: .
    command: ['jlpm', 'run', 'start-jlab']
    environment:
      PYTHONPATH: /opt/serverextension
    networks:
      - frontend
    ports:
      - 8888:8888
    volumes:
      - ../../jupyterlab-unfold/labextension:/opt/labextension/jupyterlab-unfold
      - ../../jupyterlab-unfold:/opt/serverextension

  e2e:
    # docker must match playwright version in ui-tests/package.json
    image: mcr.microsoft.com/playwright:v1.14.0-focal
    entrypoint:
      [
        '/tmp/e2e-tests/prepare.sh',
        'jupyterlab:8888',
        '--strict',
        '--timeout=60',
        '--',
      ]
    command: ['npx', 'playwright', 'test']
    environment:
      # JupyterLab URL
      TARGET_URL: http://jupyterlab:8888
    # See https://playwright.dev/docs/docker/#run-the-image
    ipc: host
    networks:
      - frontend
    depends_on:
      - lab
    volumes:
      - ..:/tmp/e2e-tests
      - ../ui-tests:/opt/ui-tests
    working_dir: /opt/ui-tests

networks:
  frontend:
