name: Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - '*'

defaults:
  run:
    shell: bash -l {0}

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Mamba
      uses: mamba-org/provision-with-micromamba@main

    - name: Build the extension
      run: |
        set -eux
        yarn
        yarn run eslint:check
        python -m pip install .

    - name: Check installation
      run: |
        test -d $CONDA_PREFIX/share/jupyter/labextensions/jupyterlab-unfold
        test -f $CONDA_PREFIX/share/jupyter/labextensions/jupyterlab-unfold/package.json

        jupyter labextension list 2>&1 | grep -ie "jupyterlab-unfold.*OK"
        python -m jupyterlab.browser_check

        check-manifest -v

    - name: UI tests
      run: |
        docker-compose -f ./docker/docker-compose.yml down || true
        docker-compose -f ./docker/docker-compose.yml pull -q || true
        docker-compose -f ./docker/docker-compose.yml build
        docker-compose -f ./docker/docker-compose.yml run --rm e2e
      working-directory: ui-tests

